# Generated by Django 5.1.7 on 2025-03-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_course_requires_enrollment_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.st_assignment')),
            ],
            options={
                'verbose_name': 'Student Submission',
                'verbose_name_plural': 'Student Submissions',
                'ordering': ['-submission_date'],
                'unique_together': {('assignment', 'student_name')},
            },
        ),
    ]
